### ISSUE TITLE
Can we change _allValues?

### ISSUE THREAD

**Issue by chang-ran** [smartnsoft/FlappyTranslator#27]
change: static Map<String, Map<String, String>> _allValues  ---> static final Map<String, Map<String, String>> allValues
so that we can get strings in any locale from allValues.

**Comment by defuncart** [comment]
@chang-ran This is planned for version 2.0. In the meantime, there is a proof of concept on [this branch](https://github.com/defuncart/flappy_translator/tree/feature/localized-values-option).

The following option

```yaml
flappy_translator:
  exposeLocalizedValues: true
```

will generate

```dart
static Map<String, String> get localizedValues => _localizedValues;
```

You can add git dependencies to pubspec as follows:

```yaml
flappy_translator:
   git:
        url: https://github.com/defuncart/flappy_translator
        ref: feature/localized-values-option
```
